#!/bin/sh

# creates a symlink, backing up any existing file
link() {
  sourcePath=$1;
  symlinkPath=$2;

  if [ -e "$symlinkPath" ]; then
    mv "$symlinkPath" "$symlinkPath.bak"
  fi

  ln -s "$sourcePath" "$symlinkPath"
}

# creates symlinks to dotfiles
link $(pwd)/profile $HOME/.profile
link $(pwd)/profile.d $HOME/.profile.d
link $(pwd)/tmux.conf $HOME/.tmux.conf
link $(pwd)/vim $HOME/.vim
link $(pwd)/vimrc $HOME/.vimrc
link $(pwd)/gitconfig $HOME/.gitconfig

# installs vim plugin manager
curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall

# installs ycm languages
(cd $HOME/.vim/packages/YouCompleteMe && ./install.py --all)
