#!/bin/sh

link() {
  sourcePath=$1;
  symlinkPath=$2;

  if [ -e "$symlinkPath" ]; then
    mv "$symlinkPath" "$symlinkPath.bak"
  fi

  ln -s "$sourcePath" "$symlinkPath"
}

link profile $HOME/.profile
link profile.d $HOME/.profile.d
link tmux.conf $HOME/.tmux.conf
link vim $HOME/.vim
link vimrc $HOME/.vimrc

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall
